# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  (?x)(
  ^cmake-build-debug/ |
  ^build/ |
  ^devel/ |
  ^install/ |
  setup.py$
  )

repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
        -   id: check-docstring-first
        -   id: check-executables-have-shebangs
        -   id: check-merge-conflict
        -   id: check-shebang-scripts-are-executable
        -   id: check-toml
        -   id: check-xml


  -   repo: https://github.com/hadolint/hadolint
      rev: v2.12.0
      hooks:
        - id: hadolint-docker
          name: Lint Dockerfiles
          description: Runs hadolint Docker image to lint Dockerfiles
          language: docker_image
          types: ["dockerfile"]
          args: [--config, .hadolint.yaml]